package com.devyash.healthcaredoctorsapp.others

object Constants {

    // Tags
    const val TAG = "HEALTHCARETAGEFORLOGGING"
    const val AUTHVERIFICATIONTAG = "AUTHVERIFICATIONTAG"
    const val FACEBOOKTEST = "FACEBOOKTEST"
    const val MAINFRAGMENTTAG = "MAINFRAGMENTTAG"
    const val HEADERLAYOUTTAG = "HEADERLAYOUTTAG"
    const val FETCHAPPOINTMENTS = "FETCHAPPOINTMENTS"
    const val DELETESLOT = "DELETESLOT"

    // FirebaseMessaging
    const val FIREBASEMESSAGINTOKEN = "FIREBASEMESSAGINTOKEN"

    // Chats
    const val CHATROOMTESTING = "CHATROOMTESTING"
    const val RECENTCHATS = "RECENTCHATS"
    // Coundown Time
    const val COUNTDOWNTIMEINMINUTE = 1

    // Firestore
    const val FIRESTOREDATASTATUS = "FIRESTOREDATASTATUS"
    const val STORAGEFAILURE = "STORAGEFAILURE"

    // Slot
    const val SLOTTESTING = "SLOTTESTING"
    const val GETTINGSLOTSFROMFIREBASE = "GETTINGSLOTSFROMFIREBASE"
}